[profile.dev]
opt-level = 0

[profile.release]
opt-level = "s"

[target.riscv64gc-unknown-none-elf]
runner = "tools/run.sh"

[build]
target = "targets/riscv64gc-unknown-none-elf.json"

[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]
unstable-options = true