schema_version = 2

[project]
name = "scarlet-aarch64-limine-desktop"

[kernel]
package = "scarlet"
source = "../../kernel"
target = "aarch64-unknown-none-elf"
target_json = "../../kernel/targets/aarch64-unknown-none-elf.json"

[kernel.features]
network = true
user-fpu = true
user-vector = true
hypervisor = true
limine = true
profiler = false

[modules]
"scarlet-module-prototype" = { path = "../../modules/scarlet-module-prototype", enabled = false }

[images]

[images.initramfs]
format = "newc"
output = ".scarlet/images/initramfs-aarch64-desktop.cpio"

[[images.initramfs.layers]]
kind = "bundle"
path = "../../bundles/base/bundle.toml"

[[images.initramfs.layers]]
kind = "bundle"
path = "../../bundles/cli-utils/bundle.toml"

[images.rootfs]
format = "ext2"
output = ".scarlet/images/rootfs-aarch64-desktop.ext2"

[[images.rootfs.layers]]
kind = "bundle"
path = "../../bundles/desktop/bundle.toml"

[images.boot]
format = "limine-uefi"
output = ".scarlet/images/limine-aarch64-desktop.img"
cmdline = "console=ttyAMA0"
deps = ["initramfs"]

[[images.boot.layers]]
kind = "image"
source = "initramfs"
to = "/boot/initramfs"

[runner]
command = "tools/run.sh"
