[env]
# Environment variable settings for build
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true
CARGO_MAKE_WORKSPACE_INCLUDE_MEMBERS = ["kernel", "user/lib", "user/bin"]

[config]
default_task = "build"
skip_core_tasks = true

[tasks.build]
description = "Build all components (default: debug)"
dependencies = ["build-debug"]

[tasks.build-debug]
description = "Build all components in debug mode"
dependencies = ["build-kernel-debug", "build-userlib-debug", "build-userbin-debug", "build-initramfs-debug"]

[tasks.build-release]
description = "Build all components in release mode"
dependencies = ["build-kernel-release", "build-userlib-release", "build-userbin-release", "build-initramfs-release"]

[tasks.build-kernel]
description = "Build the kernel (default: debug)"
dependencies = ["build-kernel-debug"]

[tasks.build-kernel-debug]
description = "Build the kernel in debug mode"
cwd = "kernel"
command = "cargo"
args = ["build"]

[tasks.build-kernel-release]
description = "Build the kernel in release mode"
cwd = "kernel"
command = "cargo"
args = ["build", "--release"]

[tasks.build-userlib]
description = "Build user libraries (default: debug)"
dependencies = ["build-userlib-debug"]

[tasks.build-userlib-debug]
description = "Build user libraries in debug mode"
cwd = "user/lib"
command = "cargo"
args = ["build"]

[tasks.build-userlib-release]
description = "Build user libraries in release mode"
cwd = "user/lib"
command = "cargo"
args = ["build", "--release"]

[tasks.build-userbin]
description = "Build user programs (default: debug)"
dependencies = ["build-userbin-debug"]

[tasks.build-userbin-debug]
description = "Build user programs in debug mode"
cwd = "user/bin"
command = "cargo"
args = ["make", "build"]
dependencies = ["build-userlib-debug"]

[tasks.build-userbin-release]
description = "Build user programs in release mode"
cwd = "user/bin"
command = "cargo"
args = ["make", "build-release"]
dependencies = ["build-userlib-release"]

[tasks.clean]
description = "Clean all build artifacts"
dependencies = ["clean-kernel", "clean-userlib", "clean-userbin", "clean-initramfs"]

[tasks.clean-kernel]
description = "Clean kernel build artifacts"
cwd = "kernel"
command = "cargo"
args = ["clean"]

[tasks.clean-userlib]
description = "Clean user library build artifacts"
cwd = "user/lib"
command = "cargo"
args = ["clean"]

[tasks.clean-userbin]
description = "Clean user program build artifacts"
cwd = "user/bin"
command = "cargo"
args = ["clean"]

[tasks.test]
description = "Run tests"
dependencies = ["test-kernel"]

[tasks.test-kernel]
description = "Run kernel tests"
cwd = "kernel"
command = "cargo"
args = ["test"]
dependencies = ["build-initramfs"]

[tasks.run]
description = "Run the kernel in release mode"
cwd = "kernel"
command = "cargo"
args = ["run", "--release"]
dependencies = ["build-release"]

[tasks.debug]
description = "Run the kernel in debug mode"
cwd = "kernel"
command = "./tools/debug.sh"
dependencies = ["build-debug"]

[tasks.doc]
description = "Generate documentation for all components"
dependencies = ["doc-kernel", "doc-userlib"]

[tasks.doc-kernel]
description = "Generate kernel documentation"
cwd = "kernel"
command = "cargo"
args = ["doc", "--no-deps", "--document-private-items"]

[tasks.doc-userlib]
description = "Generate user library documentation"
cwd = "user/lib"
command = "cargo"
args = ["doc", "--no-deps"]

[tasks.build-initramfs]
description = "Create initramfs archive (default: debug)"
cwd = "mkfs"
command = "sh"
args = ["make_initramfs.sh"]
dependencies = ["build-userbin-debug"]

[tasks.build-initramfs-release]
description = "Create initramfs archive in release mode"
cwd = "mkfs"
command = "sh"
args = ["make_initramfs.sh"]
dependencies = ["build-userbin-release"]

[tasks.build-initramfs-debug]
description = "Create initramfs archive in debug mode"
cwd = "mkfs"
command = "sh"
args = ["make_initramfs.sh"]
dependencies = ["build-userbin-debug"]

[tasks.clean-initramfs]
description = "Clean initramfs archive"
cwd = "mkfs"
command = "sh"
args = ["clean_initramfs.sh"]
