# Scarlet Experimental Bundle
# Experimental features and applications for testing and development.

[[layers]]
kind = "copy"
source = "fs"
to = "/"

[[layers]]
kind = "cargo"
source = { git = "https://github.com/petitstrawberry/yt-for-scarlet" }
package = "yt"
bin = "yt"
to = "/system/scarlet/bin/yt"

[[layers]]
kind = "cargo"
source = { git = "https://github.com/petitstrawberry/yt-for-scarlet" }
package = "yt-gui"
bin = "yt-gui"
to = "/system/scarlet/bin/yt-gui"

[[layers]]
kind = "cargo"
source = { git = "https://github.com/petitstrawberry/carmine" }
package = "carmine"
bin = "carmine"
to = "/system/scarlet/bin/carmine"