# Scarlet Experimental Bundle
# Experimental features and applications for testing and development.

[[layers]]
kind = "copy"
source = "fs"
to = "/"

[[layers]]
kind = "cargo"
source = { git = "https://github.com/petitstrawberry/moonlight-scarlet.git", rev = "c2523a4d86054c32e20671b069a0f742a7fafcc5" }
package = "moonlight"
bin = "moonlight"
to = "/bin/moonlight"

[[layers]]
kind = "cargo"
source = "../../user/video_player"
package = "video_player"
bin = "video-player"
default-features = false
features = ["av1-stateful-hw", "h264-stateful-hw", "h264-stateless-hw", "mp4-aac"]
replace = true
to = "/bin/video-player"

[[layers]]
kind = "cargo"
source = { git = "https://github.com/petitstrawberry/yt-for-scarlet", rev = "37346315dbfcd0c4102da620f7087c253babf184" }
package = "yt"
bin = "yt"
to = "/bin/yt"

[[layers]]
kind = "cargo"
source = { git = "https://github.com/petitstrawberry/yt-for-scarlet", rev = "37346315dbfcd0c4102da620f7087c253babf184" }
package = "yt-gui"
bin = "yt-gui"
to = "/bin/yt-gui"

[[layers]]
kind = "cargo"
source = "../../user/std-bin"
package = "scarlet-std-bin"
bin = "axum-demo"
to = "/bin/axum-demo"

[[layers]]
kind = "cargo"
source = "../../user/std-bin"
package = "scarlet-std-bin"
bin = "reqwest-demo"
to = "/bin/reqwest-demo"

[[layers]]
kind = "cargo"
source = "../../user/tonic-demo"
package = "scarlet-tonic-demo"
bin = "tonic-server"
to = "/bin/tonic-server"

[[layers]]
kind = "cargo"
source = "../../user/tonic-demo"
package = "scarlet-tonic-demo"
bin = "tonic-client"
to = "/bin/tonic-client"

[[layers]]
kind = "cargo"
source = "../../user/websocket-demo"
package = "scarlet-websocket-demo"
bin = "ws-server"
to = "/bin/ws-server"

[[layers]]
kind = "cargo"
source = "../../user/websocket-demo"
package = "scarlet-websocket-demo"
bin = "ws-client"
to = "/bin/ws-client"

[[layers]]
kind = "cargo"
source = { git = "https://github.com/petitstrawberry/blitz", rev = "c26e20dfff971941486ca9f50c8dcd332ec404da" }
subdir = "apps/scarlet-browser"
package = "blitz-scarlet-browser"
bin = "blitz"
to = "/bin/blitz"

[[layers]]
kind = "bundle"
source = { git = "https://github.com/petitstrawberry/resonara", rev = "66554fb762efc32f0640fe16ab7024780a84b323" }
bundle = "platforms/scarlet/bundle.toml"

[[layers]]
kind = "bundle"
source = { git = "https://github.com/petitstrawberry/easyrpg-player-scarlet.git", rev = "51b264e6a04fd945525f4624e3f2fa29150b9983" }

[[layers]]
kind = "bundle"
source = { git = "https://github.com/petitstrawberry/scarlet-bundle-linux-games.git", rev = "6f856392be9e42171339ae1633b2fd5e9fbe2e49" }
subdir = "bundles/openttd"
