# Scarlet Experimental Bundle
# Experimental features and applications for testing and development.

[[layers]]
kind = "copy"
source = "fs"
to = "/"

[[layers]]
kind = "cargo"
source = "../../user/video_player"
package = "video_player"
bin = "video-player"
default-features = false
features = ["av1-stateful-hw", "h264-stateful-hw", "h264-stateless-hw", "mp4-aac"]
replace = true
to = "/system/scarlet/bin/video-player"

[[layers]]
kind = "cargo"
source = { git = "https://github.com/petitstrawberry/yt-for-scarlet" }
package = "yt"
bin = "yt"
to = "/system/scarlet/bin/yt"

[[layers]]
kind = "cargo"
source = { git = "https://github.com/petitstrawberry/yt-for-scarlet" }
package = "yt-gui"
bin = "yt-gui"
to = "/system/scarlet/bin/yt-gui"

[[layers]]
kind = "cargo"
source = "../../user/std-bin"
package = "scarlet-std-bin"
bin = "axum-demo"
to = "/system/scarlet/bin/axum-demo"

[[layers]]
kind = "cargo"
source = "../../user/std-bin"
package = "scarlet-std-bin"
bin = "reqwest-demo"
to = "/system/scarlet/bin/reqwest-demo"

[[layers]]
kind = "cargo"
source = "../../user/tonic-demo"
package = "scarlet-tonic-demo"
bin = "tonic-server"
to = "/system/scarlet/bin/tonic-server"

[[layers]]
kind = "cargo"
source = "../../user/tonic-demo"
package = "scarlet-tonic-demo"
bin = "tonic-client"
to = "/system/scarlet/bin/tonic-client"

[[layers]]
kind = "cargo"
source = "../../user/websocket-demo"
package = "scarlet-websocket-demo"
bin = "ws-server"
to = "/system/scarlet/bin/ws-server"

[[layers]]
kind = "cargo"
source = "../../user/websocket-demo"
package = "scarlet-websocket-demo"
bin = "ws-client"
to = "/system/scarlet/bin/ws-client"

[[layers]]
kind = "cargo"
source = { git = "https://github.com/petitstrawberry/blitz", rev = "c26e20dfff971941486ca9f50c8dcd332ec404da" }
subdir = "apps/scarlet-browser"
package = "blitz-scarlet-browser"
bin = "blitz"
to = "/system/scarlet/bin/blitz"

[[layers]]
kind = "cargo"
source = { git = "https://github.com/petitstrawberry/myrica", rev = "6deb1dbd582e56393db3958e00873d15a1312c5e" }
package = "myrica"
bin = "myrica"
to = "/system/scarlet/bin/myrica"
