schema_version = 1

[image]
name = "microvm-host"
description = "Host image for the Scarlet microVM."
compatible_machines = ["qemu-aarch64-virt"]

packagegroups = ["boot"]
packages = ["microvm-init"]

[initramfs]
format = "newc"
output = ".scarlet/images/initramfs-aarch64.cpio"

[rootfs]
format = "ext2"
output = ".scarlet/images/rootfs-aarch64.ext2"

[[files]]
source = "initramfs"
destination = "/"
