[package]
name = "scarlet_std"
version = "0.15.0"
edition = "2024"

[lib]
name = "scarlet_std"
path = "src/lib.rs"
test = false

[[test]]
name = "std_tests"
path = "tests/runner.rs"
harness = false

[features]
# Enables allocator overlap/invariant checks even in release builds.
alloc_debug = []
# Enable this when building test binaries (tests/runner.rs)
test_harness = []

[dependencies]
talc = { version = "4.4", default-features = false, features = ["lock_api"] }
spin = { version = "0.10.0", default-features = false, features = ["lock_api", "mutex", "spin_mutex"] }
hashbrown = "0.16.1"

[build]
target = "../../../targets/riscv64gc-unknown-scarlet-elf.json" 