//! Scarlet userspace codec request builders.
//!
//! This crate keeps codec parsing and DPB management in userspace. Kernel
//! video backends receive prepared request parameters and only lower them to
//! hardware-specific command streams.

#![no_std]

extern crate alloc;

/// H.264/AVC stateless request construction.
pub mod h264;
/// VP9 stateless request construction.
pub mod vp9;

pub use h264::{
    H264PreparedAccessUnit, H264RequestContext, SCARLET_VIDEO_H264_DECODE_PARAM_FLAG_IDR,
    SCARLET_VIDEO_H264_DPB_FLAG_LONG_TERM, SCARLET_VIDEO_H264_DPB_FLAG_VALID,
    SCARLET_VIDEO_H264_PPS_FLAG_BOTTOM_FIELD_PIC_ORDER_IN_FRAME_PRESENT,
    SCARLET_VIDEO_H264_PPS_FLAG_CONSTRAINED_INTRA_PRED,
    SCARLET_VIDEO_H264_PPS_FLAG_DEBLOCKING_FILTER_CONTROL_PRESENT,
    SCARLET_VIDEO_H264_PPS_FLAG_ENTROPY_CODING_MODE,
    SCARLET_VIDEO_H264_PPS_FLAG_REDUNDANT_PIC_CNT_PRESENT,
    SCARLET_VIDEO_H264_PPS_FLAG_TRANSFORM_8X8_MODE, SCARLET_VIDEO_H264_PPS_FLAG_WEIGHTED_PRED,
    SCARLET_VIDEO_H264_SLICE_FLAG_DIRECT_SPATIAL_MV_PRED,
    SCARLET_VIDEO_H264_SLICE_FLAG_REF_LISTS_PRESENT,
    SCARLET_VIDEO_H264_SPS_FLAG_DELTA_PIC_ORDER_ALWAYS_ZERO,
    SCARLET_VIDEO_H264_SPS_FLAG_DIRECT_8X8_INFERENCE, SCARLET_VIDEO_H264_SPS_FLAG_FRAME_CROPPING,
    SCARLET_VIDEO_H264_SPS_FLAG_FRAME_MBS_ONLY,
    SCARLET_VIDEO_H264_SPS_FLAG_GAPS_IN_FRAME_NUM_VALUE_ALLOWED,
    SCARLET_VIDEO_H264_SPS_FLAG_MB_ADAPTIVE_FRAME_FIELD,
    SCARLET_VIDEO_H264_SPS_FLAG_QPPRIME_Y_ZERO_TRANSFORM_BYPASS,
    SCARLET_VIDEO_H264_SPS_FLAG_SEPARATE_COLOUR_PLANE, ScarletVideoH264DecodeParams,
    ScarletVideoH264DpbEntry, ScarletVideoH264Pps, ScarletVideoH264PredWeights,
    ScarletVideoH264Reference, ScarletVideoH264ScalingMatrix, ScarletVideoH264SliceParams,
    ScarletVideoH264Sps, ScarletVideoH264StatelessParams, ScarletVideoH264WeightFactors,
};

pub use vp9::{
    SCARLET_VIDEO_VP9_FRAME_FLAG_ALLOW_HIGH_PREC_MV,
    SCARLET_VIDEO_VP9_FRAME_FLAG_COLOR_RANGE_FULL_SWING,
    SCARLET_VIDEO_VP9_FRAME_FLAG_ERROR_RESILIENT, SCARLET_VIDEO_VP9_FRAME_FLAG_INTRA_ONLY,
    SCARLET_VIDEO_VP9_FRAME_FLAG_KEY_FRAME, SCARLET_VIDEO_VP9_FRAME_FLAG_PARALLEL_DEC_MODE,
    SCARLET_VIDEO_VP9_FRAME_FLAG_REFRESH_FRAME_CTX, SCARLET_VIDEO_VP9_FRAME_FLAG_SHOW_FRAME,
    SCARLET_VIDEO_VP9_FRAME_FLAG_X_SUBSAMPLING, SCARLET_VIDEO_VP9_FRAME_FLAG_Y_SUBSAMPLING,
    SCARLET_VIDEO_VP9_INTERP_FILTER_BILINEAR, SCARLET_VIDEO_VP9_INTERP_FILTER_EIGHTTAP,
    SCARLET_VIDEO_VP9_INTERP_FILTER_EIGHTTAP_SHARP,
    SCARLET_VIDEO_VP9_INTERP_FILTER_EIGHTTAP_SMOOTH, SCARLET_VIDEO_VP9_INTERP_FILTER_SWITCHABLE,
    SCARLET_VIDEO_VP9_LOOP_FILTER_FLAG_DELTA_ENABLED,
    SCARLET_VIDEO_VP9_LOOP_FILTER_FLAG_DELTA_UPDATE, SCARLET_VIDEO_VP9_MAX_TILES,
    SCARLET_VIDEO_VP9_PROBABILITY_BYTES, SCARLET_VIDEO_VP9_REFERENCE_MODE_COMPOUND_REFERENCE,
    SCARLET_VIDEO_VP9_REFERENCE_MODE_SELECT, SCARLET_VIDEO_VP9_REFERENCE_MODE_SINGLE_REFERENCE,
    SCARLET_VIDEO_VP9_RESET_FRAME_CTX_ALL, SCARLET_VIDEO_VP9_RESET_FRAME_CTX_NONE,
    SCARLET_VIDEO_VP9_RESET_FRAME_CTX_SPEC,
    SCARLET_VIDEO_VP9_SEGMENTATION_FLAG_ABS_OR_DELTA_UPDATE,
    SCARLET_VIDEO_VP9_SEGMENTATION_FLAG_ENABLED,
    SCARLET_VIDEO_VP9_SEGMENTATION_FLAG_TEMPORAL_UPDATE,
    SCARLET_VIDEO_VP9_SEGMENTATION_FLAG_UPDATE_DATA,
    SCARLET_VIDEO_VP9_SEGMENTATION_FLAG_UPDATE_MAP, SCARLET_VIDEO_VP9_SIGN_BIAS_ALT,
    SCARLET_VIDEO_VP9_SIGN_BIAS_GOLDEN, SCARLET_VIDEO_VP9_SIGN_BIAS_LAST,
    SCARLET_VIDEO_VP9_TX_MODE_ALLOW_8X8, SCARLET_VIDEO_VP9_TX_MODE_ALLOW_16X16,
    SCARLET_VIDEO_VP9_TX_MODE_ALLOW_32X32, SCARLET_VIDEO_VP9_TX_MODE_ONLY_4X4,
    SCARLET_VIDEO_VP9_TX_MODE_SELECT, ScarletVideoVp9FrameParams, ScarletVideoVp9LoopFilter,
    ScarletVideoVp9Probabilities, ScarletVideoVp9Quantization, ScarletVideoVp9Segmentation,
    ScarletVideoVp9StatelessParams, ScarletVideoVp9Tile, ScarletVideoVp9Tiles, Vp9PreparedFrame,
    Vp9RequestContext,
};
