[profile.dev]
opt-level = 3

[profile.test]
opt-level = 3

[target.aarch64-unknown-none]
rustflags = ["-T", "lds/aarch64_limine.ld"]
runner = "tools/run.sh"

[target.aarch64-unknown-none-elf]
runner = "tools/run.sh"
rustflags = [
	"-C", "no-vectorize-loops",
	"-C", "no-vectorize-slp",
]

[build]
target = "../../kernel/targets/aarch64-unknown-none-elf.json"

[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]
unstable-options = true
