schema_version = 1

[workspace]
name = "aarch64-microvm"

[defaults]
machine = "qemu-aarch64-virt"
distro = "microvm"
image = "microvm-host"
profile = "release"

[[layers]]
name = "bsp-qemu-aarch64"
path = "../../layers/bsp-qemu-aarch64"
priority = 50

[[layers]]
name = "distro-microvm"
path = "../../layers/distro-microvm"
priority = 100
