// Auto-generated by xtask
// DO NOT EDIT MANUALLY

/// Wrapper for the `kernel_print` kernel function
pub fn kernel_print() -> () {
    let func_ptr = unsafe { crate::API_SYMBOLS.kernel_print };
    if func_ptr.is_null() {
        panic!("API function kernel_print not initialized");
    }
    let f: fn() -> () = unsafe { core::mem::transmute(func_ptr) };
    f()
}

/// Wrapper for the `kernel_shutdown` kernel function
pub fn kernel_shutdown() -> ! {
    let func_ptr = unsafe { crate::API_SYMBOLS.kernel_shutdown };
    if func_ptr.is_null() {
        panic!("API function kernel_shutdown not initialized");
    }
    let f: fn() -> ! = unsafe { core::mem::transmute(func_ptr) };
    f()
}

