// Auto-generated by xtask
// DO NOT EDIT MANUALLY

#![no_std]

//! Scarlet Kernel API
//! 
//! This crate provides access to Scarlet kernel functions and types.
//! It is automatically generated from the kernel source code.

mod symbol;
pub use symbol::API_SYMBOLS;

pub mod test;
pub mod api;

/// Wrapper for the `panic` kernel function
pub fn panic() -> () {
    let func_ptr = unsafe { crate::API_SYMBOLS.panic };
    if func_ptr.is_null() {
        panic!("API function panic not initialized");
    }
    let f: fn() -> () = unsafe { core::mem::transmute(func_ptr) };
    f()
}

