// Auto-generated by xtask
// DO NOT EDIT MANUALLY

/// Wrapper for the `panic` kernel function
pub fn panic() -> () {
    let func_ptr = unsafe { crate::API_SYMBOLS.panic };
    if func_ptr.is_null() {
        panic!("API function panic not initialized");
    }
    let f: fn() -> () = unsafe { core::mem::transmute(func_ptr) };
    f()
}

