schema_version = 1

[recipe]
name = "microvm-init"
source = { path = "../../../user/bin" }
build = { kind = "cargo", package = "user-bin", bin = "microvm_init" }

[[package]]
name = "microvm-init"
files = [{ from = "dist/aarch64/microvm_init", to = "/system/scarlet/bin/init" }]
