schema_version = 1

[recipe]
name = "shell"
source = { path = "../../../user/bin" }
build = { kind = "cargo", package = "user-bin", bin = "sh" }

[[package]]
name = "shell"
files = [{ from = "dist/aarch64/sh", to = "/system/scarlet/bin/sh" }]
