# AArch64 full image using the experimental Alpine Linux view.

[[layers]]
kind = "bundle"
path = "../desktop/bundle.toml"

[[layers]]
kind = "bundle"
source = { git = "https://github.com/petitstrawberry/scarlet-bundle-alpine.git", rev = "51f973b8e4ee289cc328f636c5a66e384826ccf6" }
subdir = "bundles/rootfs"

[[layers]]
kind = "bundle"
source = { git = "https://github.com/petitstrawberry/scarlet-bundle-alpine.git", rev = "51f973b8e4ee289cc328f636c5a66e384826ccf6" }
subdir = "bundles/mozc"

[[layers]]
kind = "bundle"
path = "../experimental/bundle.toml"

[[layers]]
kind = "bundle"
path = "../rust-toolchain/bundle.toml"
