[package]
name = "scarlet"
version = "0.16.0"
edition = "2024"

[lib]
name = "scarlet"
path = "src/lib.rs"
doctest = false

[dependencies]
fdt = "0.1.5"
talc = "4.4"
hashbrown = "0.16.0"
lock_api = "0.4"
limine = "0.6"
font8x8 = { version = "0.3", default-features = false, features = ["unicode"] }

[features]
default = ["network", "user-fpu", "user-vector", "hypervisor", "limine"]
profiler = []
network = []
user-fpu = []
user-vector = []
hypervisor = []
limine = []
