[package]
name = "Scarlet"
version = "0.16.0"
edition = "2024"

[[bin]]
name = "kernel"
path = "src/main.rs"

[dependencies]
fdt = "0.1.5"
talc = "4.4"
spin = "0.10.0"
hashbrown = "0.16.0"
lazy_static = { version = "1.4.0", features = ["spin_no_std"], optional = true }
limine = "0.5"

[features]
default = ["network", "user-fpu", "user-vector", "hypervisor"]
profiler = ["dep:lazy_static"]
network = []
user-fpu = []
user-vector = []
hypervisor = []
