[package]
name = "scarlet-websocket-demo"
version = "0.1.0"
edition = "2024"
workspace = "../../.cargo"

[dependencies]
futures-util = { version = "0.3", default-features = false, features = ["sink", "std"] }
getrandom = "0.4"
scarlet-sys = { path = "../lib/scarlet-sys" }
tokio = { version = "1.53.1", features = ["macros", "net", "rt", "sync", "time"] }
tokio-tungstenite = "0.30"

[[bin]]
name = "ws-server"
path = "src/bin/ws_server.rs"

[[bin]]
name = "ws-client"
path = "src/bin/ws_client.rs"
