[package]
name = "sbus-client"
version = "0.1.0"
edition = "2024"

[features]
default = ["legacy-scarlet-std"]
legacy-scarlet-std = ["dep:scarlet-std"]
std = ["dep:scarlet-os", "scarlet-os/std"]

[dependencies]
scarlet-os = { path = "../scarlet-os", default-features = false, optional = true }
scarlet-std = { path = "../std", optional = true }
sbus = { path = "../sbus" }
