# Scarlet Full Distribution Bundle with Buildroot Linux userspace.
# Supports AArch64 and RISC-V 64.

[[layers]]
kind = "bundle"
path = "../desktop/bundle.toml"

[[layers]]
kind = "bundle"
path = "../buildroot/bundle.toml"

[[layers]]
kind = "bundle"
path = "../experimental/bundle.toml"

[[layers]]
kind = "bundle"
path = "../rust-toolchain/bundle.toml"
