[profile.dev]
opt-level = 0

[target.riscv64gc-unknown-none-elf]
runner = "tools/run.sh"


[build]
target = "riscv64gc-unknown-none-elf"
rustflags = [
    "-C", "link-arg=-Tlds/qemu_virt.ld", 
    "-C", "target-feature=-c"
]

[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]
unstable-options = true