[package]
name = "vulkan-canvas-demo"
version = "0.1.0"
edition = "2024"
workspace = "../../.cargo"
build = "build.rs"

[build-dependencies]
naga = { version = "24", features = ["wgsl-in", "spv-out"] }

[target.'cfg(target_os = "scarlet")'.dependencies]
ash = { version = "0.38", default-features = false, features = ["debug", "std"] }
scarlet-ui = { git = "https://github.com/petitstrawberry/scarlet-ui", rev = "6ef3e3c4da42898e8077b3698f08a95f9f718b8c", default-features = false, features = ["std", "platform-sws"] }
vulkan-sgfx = { git = "https://github.com/petitstrawberry/sgfx", rev = "ddf00563c617a30bbf64fa5dbe8152c852d493f9" }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(target_os, values("scarlet"))'] }
