[package]
name = "vulkan-canvas-demo"
version = "0.1.0"
edition = "2024"
workspace = "../../.cargo"
build = "build.rs"

[build-dependencies]
naga = { version = "24", features = ["wgsl-in", "spv-out"] }

[target.'cfg(target_os = "scarlet")'.dependencies]
ash = { version = "0.38", default-features = false, features = ["debug", "std"] }
scarlet-ui = { git = "https://github.com/petitstrawberry/scarlet-ui", rev = "ddad057af60a7db7f463f4c653bc0ab220dc4658", default-features = false, features = ["std", "platform-sws"] }
vulkan-sgfx = { git = "https://github.com/petitstrawberry/sgfx", rev = "d53d9b0062e18a7219fc04138cb9655cc9148e27" }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(target_os, values("scarlet"))'] }
