schema_version = 1

[distro]
name = "microvm"
vendor = "petitstrawberry"
version = "0.17.0"
system_prefix = "/system/scarlet"
default_shell = "/system/scarlet/bin/sh"
default_boot_target = "limine-uefi-aarch64"

[providers]
kernel = "scarlet-kernel"
init = "microvm-init"

[features]
network = true
hypervisor = true
