[package]
name = "sgfx"
version = "0.16.0"
edition = "2024"

[features]
default = ["scarlet-std"]
std = ["framebuffer/std", "sgfx-backend-scarlet-virgl/std"]
scarlet-std = ["framebuffer/scarlet-std", "sgfx-backend-scarlet-virgl/scarlet-std"]

[dependencies]
framebuffer = { path = "../framebuffer", default-features = false }
sgfx-backend-scarlet-virgl = { path = "../sgfx-backend-scarlet-virgl", default-features = false }

[lib]
name = "sgfx"
path = "src/lib.rs"
