[package]
name = "scarlet-ui-preview-demo"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/main.rs"

[features]
preview = []

[dependencies]
scarlet-ui = { path = "../..", default-features = false, features = ["std", "platform-winit", "preview"] }
scarlet-ui-macros = { path = "../../../scarlet-ui-macros" }
