#!/bin/bash

set -o pipefail

# Check for debug mode environment variable or command line argument
DEBUG_MODE=${SCARLET_DEBUG_MODE:-false}
KERNEL_PATH=""

# Parse command line arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --debug)
            DEBUG_MODE=true
            shift
            ;;
        *)
            # This should be the kernel binary path
            KERNEL_PATH="$1"
            shift
            ;;
    esac
done

# If no kernel path provided, try to find the default build
if [ -z "$KERNEL_PATH" ]; then
    SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    KERNEL_DIR="$(dirname "$SCRIPT_DIR")"
    
    if [ "$DEBUG_MODE" = "true" ]; then
        KERNEL_PATH="$KERNEL_DIR/target/aarch64-unknown-none-elf/debug/kernel"
    else
        # For release mode or default run
        if [ -f "$KERNEL_DIR/target/aarch64-unknown-none-elf/release/kernel" ]; then
            KERNEL_PATH="$KERNEL_DIR/target/aarch64-unknown-none-elf/release/kernel"
        else
            KERNEL_PATH="$KERNEL_DIR/target/aarch64-unknown-none-elf/debug/kernel"
        fi
    fi
fi

if [ "$DEBUG_MODE" = "true" ]; then
    echo "Starting qemu-system-aarch64 in debug mode with gdb server..."
    DEBUG_FLAGS="-gdb tcp::12345 -S"
else
    echo "Starting qemu-system-aarch64..."
    DEBUG_FLAGS=""
fi

# Find the project root by looking for Makefile.toml
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR" && cd .. && cd .. && pwd)"
INITRAMFS_PATH="$PROJECT_ROOT/mkfs/dist/initramfs-aarch64.cpio"

# Ensure initramfs exists (do NOT auto-generate here; keep behavior consistent across architectures)
if [ ! -f "$INITRAMFS_PATH" ]; then
    echo "Error: initramfs not found at $INITRAMFS_PATH"
    echo "Please build it explicitly before running QEMU. Example:"
    echo "  cargo make build-initramfs-aarch64"
    echo "  cargo make build-initramfs-release-aarch64"
    exit 1
fi

# Create temporary file for capturing output
TEMP_OUTPUT=$(mktemp)

# U-Boot binary path (built from source, see Dockerfile)
# U-Boot is configured to auto-boot using: qfw load; booti $kernel_addr_r - $fdt_addr_r
UBOOT_BIN="/opt/u-boot-aarch64.bin"

if [ ! -f "$UBOOT_BIN" ]; then
    echo "Error: U-Boot binary not found at $UBOOT_BIN"
    echo "Please build U-Boot first (see Dockerfile for instructions)"
    exit 1
fi

# Convert ELF kernel to raw binary for U-Boot booti
# The kernel already includes Linux arm64 Image header in .head.text section
KERNEL_BIN="${KERNEL_PATH}.bin"
echo "Converting kernel ELF to raw binary..."
aarch64-linux-gnu-objcopy -O binary "$KERNEL_PATH" "$KERNEL_BIN"

# Ensure U-Boot supports qfw-based boot (so we can pass initrd automatically)
# If not, attempt to rebuild U-Boot with a qfw+initrd-aware BOOTCOMMAND.
if ! strings -a "$UBOOT_BIN" | grep -q "qfw load"; then
    echo "Warning: U-Boot does not seem to include qfw support; initramfs passing may fail."
fi

# Run QEMU with U-Boot as BIOS
# - Kernel binary (with Linux Image header) is loaded at 0x40200000
# - U-Boot boots with booti command, passing DTB address in x0
# - DTB is generated by QEMU virt machine
qemu-system-aarch64 \
    -machine virt \
    -cpu cortex-a57 \
    -m 2G \
    -nographic \
    -serial mon:stdio \
    --no-reboot \
    -bios "$UBOOT_BIN" \
    -initrd "$INITRAMFS_PATH" \
    -kernel "$KERNEL_BIN" \
    $DEBUG_FLAGS | tee "$TEMP_OUTPUT"

# Capture pipeline exit codes (qemu is element 0, tee is element 1)
QEMU_EXIT_CODE=${PIPESTATUS[0]}
TEE_EXIT_CODE=${PIPESTATUS[1]}

# In debug mode, don't check for test patterns since we're debugging
if [ "$DEBUG_MODE" = "true" ]; then
    echo "Debug session ended"
    rm -f "$TEMP_OUTPUT"
    exit 0
fi

# Check for test failure patterns in output
if grep -q "\[Test Runner\] Test failed" "$TEMP_OUTPUT"; then
    echo "Test failure detected in output"
    rm -f "$TEMP_OUTPUT"
    exit 1
elif grep -q "\[Test Runner\] All .* tests passed" "$TEMP_OUTPUT"; then
    echo "All tests passed"
    rm -f "$TEMP_OUTPUT"
    exit 0
else
    echo "Could not determine test result, QEMU exit code: $QEMU_EXIT_CODE (tee: $TEE_EXIT_CODE)"
    rm -f "$TEMP_OUTPUT"
    exit $QEMU_EXIT_CODE
fi