use std::{fs, io::Write, path::Path};
use std::error::Error;
use syn::{visit::Visit, Attribute, File, Item, ItemFn, Meta, MetaNameValue};
use walkdir::WalkDir;

fn main() {
    let args: Vec<String> = std::env::args().collect();
    if args.get(1).map(|s| s == "gen-api").unwrap_or(false) {
        if let Err(e) = generate_api_symbols() {
            eprintln!("Error generating API symbols: {}", e);
            std::process::exit(1);
        }
    } else {
        eprintln!("Usage: cargo xtask gen-api");
    }
}

fn generate_api_symbols() -> Result<(), Box<dyn Error>> {
    // カーネルソースディレクトリのパス
    let kernel_src_dir = Path::new("../kernel/src");
    
    // #[export]属性付きの関数を収集
    let exported_functions = collect_exported_functions(kernel_src_dir)?;
    
    if exported_functions.is_empty() {
        println!("⚠️ No exported functions found");
        
        // テスト用のダミー関数を追加（本番環境では削除）
        let exported_functions = vec![
            ("printk".to_string(), "*const ()".to_string()),
            ("kernel_shutdown".to_string(), "*const ()".to_string()),
        ];
        generate_symbols_file(&exported_functions)?;
    } else {
        println!("✅ Found {} exported functions", exported_functions.len());
        for (name, _) in &exported_functions {
            println!("  - {}", name);
        }
        
        // シンボルファイル生成
        generate_symbols_file(&exported_functions)?;
    }

    Ok(())
}

fn generate_symbols_file(exported_functions: &[(String, String)]) -> Result<(), Box<dyn Error>> {
    // ApiSymbols構造体と初期化コードを生成
    let struct_fields = exported_functions
        .iter()
        .map(|(name, _)| format!("    pub {}: *const (),", name))
        .collect::<Vec<_>>()
        .join("\n");

    let null_assignments = exported_functions
        .iter()
        .map(|(name, _)| format!("    {}: core::ptr::null(),", name))
        .collect::<Vec<_>>()
        .join("\n");

    let output = format!(
        r#"// Auto-generated by xtask
// DO NOT EDIT MANUALLY

/// ApiSymbols - カーネルからエクスポートされた関数へのポインタを格納する構造体
/// #[export]属性マクロが付いた関数は自動的にここに登録される
#[repr(C)]
pub struct ApiSymbols {{
{struct_fields}
}}

/// グローバルなAPIシンボルテーブル（カーネル初期化時に関数ポインタが設定される）
pub static mut API_SYMBOLS: ApiSymbols = ApiSymbols {{
{null_assignments}
}};
"#,
        struct_fields = struct_fields,
        null_assignments = null_assignments,
    );

    // kernel/src/symbol.rsに出力
    let out_path = Path::new("../kernel/src/symbol.rs");
    fs::write(out_path, output)?;

    println!("✅ kernel/src/symbol.rs generated.");
    Ok(())
}

fn collect_exported_functions(src_dir: &Path) -> Result<Vec<(String, String)>, Box<dyn Error>> {
    let mut exported_functions = Vec::new();
    
    // カーネルソースツリーを再帰的に走査
    for entry in WalkDir::new(src_dir).into_iter().filter_map(|e| e.ok()) {
        let path = entry.path();
        
        // Rustソースファイルのみを処理
        if path.extension().map_or(false, |ext| ext == "rs") {
            let content = fs::read_to_string(path)?;
            
            // synでソースコードをパース
            if let Ok(file) = syn::parse_file(&content) {
                let mut visitor = ExportVisitor::default();
                visitor.visit_file(&file);
                
                // #[export]属性付き関数をリストに追加
                for (name, sig) in visitor.exports {
                    exported_functions.push((name, sig));
                }
            }
        }
    }
    
    Ok(exported_functions)
}

#[derive(Default)]
struct ExportVisitor {
    exports: Vec<(String, String)>,
}

impl<'ast> Visit<'ast> for ExportVisitor {
    fn visit_item_fn(&mut self, node: &'ast ItemFn) {
        // 関数に#[export]属性があるか確認
        if node.attrs.iter().any(|attr| is_export_attr(attr)) {
            let name = node.sig.ident.to_string();
            let sig = "*const ()".to_string(); // 常に関数ポインタとして扱う
            self.exports.push((name, sig));
        }
        
        // デフォルトの走査を続行
        syn::visit::visit_item_fn(self, node);
    }
}

fn is_export_attr(attr: &Attribute) -> bool {
    // 'export'という名前の属性を検索
    if attr.path().is_ident("export") {
        return true;
    }
    
    // // また、#[unsafe(export_name = "...")] のようなものも検出する
    // if attr.path().is_ident("unsafe") {
    //     // 属性の中のexport_nameを検索
    //     if let Ok(meta) = attr.meta.require_list() {
    //         if let Ok(nested) = meta.parse_args_with(syn::punctuated::Punctuated::<syn::Meta, syn::Token![,]>::parse_terminated) {
    //             for nested_meta in nested {
    //                 if let syn::Meta::NameValue(name_value) = nested_meta {
    //                     if name_value.path.is_ident("export_name") {
    //                         return true;
    //                     }
    //                 }
    //             }
    //         }
    //     }
    // }
    
    false
}