[package]
name = "scarlet-ui"
version = "0.1.0"
edition = "2024"

[lib]
name = "scarlet_ui"
path = "src/lib.rs"

[dependencies]
sws-client = { path = "../sws-client" }
scarlet_std = { path = "../std" }
ab_glyph = { version = "0.2", default-features = false, features = ["libm"] }
scarlet-ui-macros = { path = "../scarlet-ui-macros" }

