schema_version = 2

[project]
name = "scarlet-aarch64-limine-full"

[kernel]
package = "scarlet"
source = "../../kernel"
target = "aarch64-unknown-none-elf"
target_json = "../../kernel/targets/aarch64-unknown-none-elf.json"

[kernel.features]
network = true
user-fpu = true
user-vector = true
hypervisor = true
limine = true
profiler = false

[modules]
"scarlet-module-prototype" = { path = "../../modules/scarlet-module-prototype", enabled = true }
