// Auto-generated by xtask
// DO NOT EDIT MANUALLY

/// ApiSymbols - カーネルからエクスポートされた関数へのポインタを格納する構造体
/// #[export]属性マクロが付いた関数は自動的にここに登録される
#[repr(C)]
pub struct ApiSymbols {
    pub kernel_print: *const (),
    pub kernel_shutdown: *const (),
}

/// グローバルなAPIシンボルテーブル（カーネル初期化時に関数ポインタが設定される）
pub static mut API_SYMBOLS: ApiSymbols = ApiSymbols {
    kernel_print: core::ptr::null(),
    kernel_shutdown: core::ptr::null(),
};
