[package]
name = "userprogram"
version = "0.11.1"
edition = "2024"

[[bin]]
name = "init"
path = "src/init.rs"

[[bin]]
name = "sh"
path = "src/sh.rs"

[[bin]]
name = "hello"
path = "src/hello.rs"

[[bin]]
name = "test"
path = "src/test.rs"

[dependencies]
scarlet_std = { path = "../lib" }