[package]
name = "userprogram"
version = "0.11.2"
edition = "2024"

[[bin]]
name = "init"
path = "src/init.rs"

[[bin]]
name = "sh"
path = "src/sh.rs"

[[bin]]
name = "hello"
path = "src/hello.rs"

[[bin]]
name = "test"
path = "src/test.rs"

[[bin]]
name = "xv6"
path = "src/xv6.rs"

[[bin]]
name = "env_test"
path = "src/env_test.rs"

[dependencies]
scarlet_std = { path = "../lib" }