[package]
name = "userprogram"
version = "0.15.0"
edition = "2024"

[[bin]]
name = "init"
path = "src/init.rs"

[[bin]]
name = "login"
path = "src/login.rs"

[[bin]]
name = "sh"
path = "src/sh.rs"

[[bin]]
name = "ls"
path = "src/ls.rs"

[[bin]]
name = "hello"
path = "src/hello.rs"

[[bin]]
name = "test"
path = "src/test.rs"

[[bin]]
name = "xv6"
path = "src/xv6.rs"

[[bin]]
name = "env_test"
path = "src/env_test.rs"

[[bin]]
name = "cat"
path = "src/cat.rs"

[[bin]]
name = "fb_test"
path = "src/fb_test.rs"

[dependencies]
scarlet_std = { path = "../lib/std" }
framebuffer = { path = "../lib/framebuffer" }