name: Docker Image CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be
      with:
        tool-cache: false
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: true
        swap-storage: true

    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Generate Docker cache key
      id: docker-cache-key
      run: |
        rust_rev="$(git ls-tree HEAD rust | awk '{print $3}')"
        echo "rust-rev=${rust_rev}" >> $GITHUB_OUTPUT
        echo "key=docker-cache-${{ hashFiles('Dockerfile', '.dockerignore', 'docker/entrypoint.sh', 'flake.nix', 'flake.lock', 'nix/**', 'scripts/setup-scarlet-rust-toolchain.sh') }}-${rust_rev}" >> $GITHUB_OUTPUT

    - name: Cache Docker image
      id: docker-cache
      uses: actions/cache@v3
      with:
        path: /tmp/docker-image
        key: ${{ steps.docker-cache-key.outputs.key }}

    - name: Build the Docker image
      if: steps.docker-cache.outputs.cache-hit != 'true'
      run: |
        docker build . --file Dockerfile --target ci --tag scarlet-ci \
          --build-arg SCARLET_RUST_REV="${{ steps.docker-cache-key.outputs.rust-rev }}" \
          --build-arg SCARLET_CACHIX_CACHE="${{ vars.CACHIX_CACHE_NAME }}" \
          --build-arg SCARLET_CACHIX_PUBLIC_KEY="${{ vars.CACHIX_PUBLIC_KEY }}"
        docker save scarlet-ci > /tmp/docker-image

  fmt:
    needs: docker
    runs-on: ubuntu-latest
    steps:
    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be
      with:
        tool-cache: false
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: true
        swap-storage: true

    - uses: actions/checkout@v4

    - name: Generate Docker cache key
      id: docker-cache-key
      run: |
        rust_rev="$(git ls-tree HEAD rust | awk '{print $3}')"
        echo "rust-rev=${rust_rev}" >> $GITHUB_OUTPUT
        echo "key=docker-cache-${{ hashFiles('Dockerfile', '.dockerignore', 'docker/entrypoint.sh', 'flake.nix', 'flake.lock', 'nix/**', 'scripts/setup-scarlet-rust-toolchain.sh') }}-${rust_rev}" >> $GITHUB_OUTPUT

    - name: Restore Docker image cache
      uses: actions/cache@v3
      with:
        path: /tmp/docker-image
        key: ${{ steps.docker-cache-key.outputs.key }}

    - name: Load Docker image
      run: docker load < /tmp/docker-image

    - name: Run formatting check
      env:
        SCARLET_CACHIX_CACHE: ${{ vars.CACHIX_CACHE_NAME }}
        SCARLET_CACHIX_PUBLIC_KEY: ${{ vars.CACHIX_PUBLIC_KEY }}
      run: |
        docker run \
          -e SCARLET_CACHIX_CACHE \
          -e SCARLET_CACHIX_PUBLIC_KEY \
          -e GIT_CONFIG_COUNT=1 \
          -e GIT_CONFIG_KEY_0=safe.directory \
          -e GIT_CONFIG_VALUE_0=/workspaces/Scarlet \
          -v $PWD:/workspaces/Scarlet \
          scarlet-ci cargo make fmt-check

  test-riscv64:
    needs: docker
    runs-on: ubuntu-latest
    steps:
    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be
      with:
        tool-cache: false
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: true
        swap-storage: true

    - uses: actions/checkout@v4

    - name: Generate Docker cache key
      id: docker-cache-key
      run: |
        rust_rev="$(git ls-tree HEAD rust | awk '{print $3}')"
        echo "rust-rev=${rust_rev}" >> $GITHUB_OUTPUT
        echo "key=docker-cache-${{ hashFiles('Dockerfile', '.dockerignore', 'docker/entrypoint.sh', 'flake.nix', 'flake.lock', 'nix/**', 'scripts/setup-scarlet-rust-toolchain.sh') }}-${rust_rev}" >> $GITHUB_OUTPUT

    - name: Restore Docker image cache
      uses: actions/cache@v3
      with:
        path: /tmp/docker-image
        key: ${{ steps.docker-cache-key.outputs.key }}

    - name: Load Docker image
      run: docker load < /tmp/docker-image

    - name: Build scarlet kernel (riscv64)
      env:
        SCARLET_CACHIX_CACHE: ${{ vars.CACHIX_CACHE_NAME }}
        SCARLET_CACHIX_PUBLIC_KEY: ${{ vars.CACHIX_PUBLIC_KEY }}
      run: |
        docker run \
          -e SCARLET_CACHIX_CACHE \
          -e SCARLET_CACHIX_PUBLIC_KEY \
          -e GIT_CONFIG_COUNT=1 \
          -e GIT_CONFIG_KEY_0=safe.directory \
          -e GIT_CONFIG_VALUE_0=/workspaces/Scarlet \
          -v $PWD:/workspaces/Scarlet \
          scarlet-ci cargo make build-riscv64

    - name: Test scarlet kernel (riscv64)
      env:
        SCARLET_CACHIX_CACHE: ${{ vars.CACHIX_CACHE_NAME }}
        SCARLET_CACHIX_PUBLIC_KEY: ${{ vars.CACHIX_PUBLIC_KEY }}
      run: |
        docker run \
          -e SCARLET_CACHIX_CACHE \
          -e SCARLET_CACHIX_PUBLIC_KEY \
          -e GIT_CONFIG_COUNT=1 \
          -e GIT_CONFIG_KEY_0=safe.directory \
          -e GIT_CONFIG_VALUE_0=/workspaces/Scarlet \
          -v $PWD:/workspaces/Scarlet \
          scarlet-ci cargo make test-riscv64
      timeout-minutes: 10

  test-aarch64:
    needs: docker
    runs-on: ubuntu-latest
    steps:
    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be
      with:
        tool-cache: false
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: true
        swap-storage: true

    - uses: actions/checkout@v4

    - name: Generate Docker cache key
      id: docker-cache-key
      run: |
        rust_rev="$(git ls-tree HEAD rust | awk '{print $3}')"
        echo "rust-rev=${rust_rev}" >> $GITHUB_OUTPUT
        echo "key=docker-cache-${{ hashFiles('Dockerfile', '.dockerignore', 'docker/entrypoint.sh', 'flake.nix', 'flake.lock', 'nix/**', 'scripts/setup-scarlet-rust-toolchain.sh') }}-${rust_rev}" >> $GITHUB_OUTPUT

    - name: Restore Docker image cache
      uses: actions/cache@v3
      with:
        path: /tmp/docker-image
        key: ${{ steps.docker-cache-key.outputs.key }}

    - name: Load Docker image
      run: docker load < /tmp/docker-image

    - name: Build scarlet kernel (aarch64)
      env:
        SCARLET_CACHIX_CACHE: ${{ vars.CACHIX_CACHE_NAME }}
        SCARLET_CACHIX_PUBLIC_KEY: ${{ vars.CACHIX_PUBLIC_KEY }}
      run: |
        docker run \
          -e SCARLET_CACHIX_CACHE \
          -e SCARLET_CACHIX_PUBLIC_KEY \
          -e GIT_CONFIG_COUNT=1 \
          -e GIT_CONFIG_KEY_0=safe.directory \
          -e GIT_CONFIG_VALUE_0=/workspaces/Scarlet \
          -v $PWD:/workspaces/Scarlet \
          scarlet-ci cargo make build-aarch64

    - name: Test scarlet kernel (aarch64)
      env:
        SCARLET_CACHIX_CACHE: ${{ vars.CACHIX_CACHE_NAME }}
        SCARLET_CACHIX_PUBLIC_KEY: ${{ vars.CACHIX_PUBLIC_KEY }}
      run: |
        docker run \
          -e SCARLET_CACHIX_CACHE \
          -e SCARLET_CACHIX_PUBLIC_KEY \
          -e GIT_CONFIG_COUNT=1 \
          -e GIT_CONFIG_KEY_0=safe.directory \
          -e GIT_CONFIG_VALUE_0=/workspaces/Scarlet \
          -v $PWD:/workspaces/Scarlet \
          scarlet-ci cargo make test-aarch64
      timeout-minutes: 10
