name: Docker Image CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:

  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    # Dockerfile と関連ファイルのハッシュを計算
    - name: Generate Docker cache key
      id: docker-cache-key
      run: echo "key=docker-cache-${{ hashFiles('Dockerfile') }}" >> $GITHUB_OUTPUT

    # Docker キャッシュを復元
    - name: Cache Docker image
      id: docker-cache
      uses: actions/cache@v3
      with:
        path: /tmp/docker-image
        key: ${{ steps.docker-cache-key.outputs.key }}
    
    # キャッシュがない場合のみビルド
    - name: Build the Docker image
      if: steps.docker-cache.outputs.cache-hit != 'true'
      run: |
        docker build . --file Dockerfile --tag scarlet-dev
        docker save scarlet-dev > /tmp/docker-image
    
    # キャッシュがある場合はロード
    - name: Load cached Docker image
      if: steps.docker-cache.outputs.cache-hit == 'true'
      run: docker load < /tmp/docker-image

    - name: Build scarlet kernel 
      run: docker run -v $PWD:/workspaces/Scarlet scarlet-dev cargo build
      
    - name: Test scarlet kernel
      run: docker run -v $PWD:/workspaces/Scarlet scarlet-dev bash /workspaces/Scarlet/tools/test.sh
