[[layers]]
kind = "cargo"
source = "../../user/std-bin"
bin = "abi-run"
to = "/bin/abi-run"

[[layers]]
kind = "cargo"
source = "../../user/std-bin"
bin = "ls"
to = "/bin/ls"

[[layers]]
kind = "cargo"
source = "../../user/std-bin"
bin = "cat"
to = "/bin/cat"

[[layers]]
kind = "cargo"
source = "../../user/std-bin"
bin = "rm"
to = "/bin/rm"

[[layers]]
kind = "cargo"
source = "../../user/std-bin"
bin = "resolve"
to = "/bin/resolve"

[[layers]]
kind = "cargo"
source = "../../user/std-bin"
bin = "nc"
to = "/bin/nc"

[[layers]]
kind = "cargo"
source = "../../user/std-bin"
bin = "ping"
to = "/bin/ping"

[[layers]]
kind = "cargo"
source = "../../user/std-bin"
bin = "netcfg"
to = "/bin/netcfg"

[[layers]]
kind = "cargo"
source = "../../user/std-bin"
bin = "watch"
to = "/bin/watch"

[[layers]]
kind = "cargo"
source = "../../user/std-bin"
bin = "date"
to = "/bin/date"

[[layers]]
kind = "cargo"
source = "../../user/std-bin"
bin = "fb-test"
to = "/bin/fb-test"
