[[layers]]
kind = "cargo"
source = "../../user/std-bin"
bin = "ls"
to = "/system/scarlet/bin/ls"

[[layers]]
kind = "cargo"
source = "../../user/std-bin"
bin = "cat"
to = "/system/scarlet/bin/cat"

[[layers]]
kind = "cargo"
source = "../../user/std-bin"
bin = "rm"
to = "/system/scarlet/bin/rm"

[[layers]]
kind = "cargo"
source = "../../user/std-bin"
bin = "resolve"
to = "/system/scarlet/bin/resolve"

[[layers]]
kind = "cargo"
source = "../../user/std-bin"
bin = "nc"
to = "/system/scarlet/bin/nc"

[[layers]]
kind = "cargo"
source = "../../user/std-bin"
bin = "ping"
to = "/system/scarlet/bin/ping"

[[layers]]
kind = "cargo"
source = "../../user/std-bin"
bin = "netcfg"
to = "/system/scarlet/bin/netcfg"

[[layers]]
kind = "cargo"
source = "../../user/std-bin"
bin = "watch"
to = "/system/scarlet/bin/watch"

[[layers]]
kind = "cargo"
source = "../../user/std-bin"
bin = "date"
to = "/system/scarlet/bin/date"

[[layers]]
kind = "cargo"
source = "../../user/std-bin"
bin = "fb-test"
to = "/system/scarlet/bin/fb-test"
