[package]
name = "scarlet-std-bin"
version = "0.1.0"
edition = "2024"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[[bin]]
name = "hello"
path = "src/hello.rs"

[[bin]]
name = "cat"
path = "src/cat.rs"

[[bin]]
name = "ls"
path = "src/ls.rs"

[[bin]]
name = "rm"
path = "src/rm.rs"

[[bin]]
name = "env_test"
path = "src/env_test.rs"

[[bin]]
name = "tcp_client"
path = "src/tcp_client.rs"

[[bin]]
name = "tcp_server"
path = "src/tcp_server.rs"

[[bin]]
name = "udp_client"
path = "src/udp_client.rs"

[[bin]]
name = "udp_server"
path = "src/udp_server.rs"

[[bin]]
name = "ansi_banner"
path = "src/ansi_banner.rs"

[[bin]]
name = "httpd"
path = "src/httpd.rs"
