[package]
name = "scarlet-std-bin"
version = "0.1.0"
edition = "2024"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
scarlet-os = { path = "../lib/scarlet-os" }
scarlet-sys = { path = "../lib/scarlet-sys" }
rust_h264 = { git = "https://github.com/petitstrawberry/rust_h264.git", rev = "edcf83ee2c99fa0087fa2d85a492a4c313e11ed0", default-features = false }

[[bin]]
name = "hello"
path = "src/hello.rs"

[[bin]]
name = "cat"
path = "src/cat.rs"

[[bin]]
name = "ls"
path = "src/ls.rs"

[[bin]]
name = "rm"
path = "src/rm.rs"

[[bin]]
name = "env_test"
path = "src/env_test.rs"

[[bin]]
name = "tcp_client"
path = "src/tcp_client.rs"

[[bin]]
name = "tcp_server"
path = "src/tcp_server.rs"

[[bin]]
name = "udp_client"
path = "src/udp_client.rs"

[[bin]]
name = "udp_server"
path = "src/udp_server.rs"

[[bin]]
name = "ansi_banner"
path = "src/ansi_banner.rs"

[[bin]]
name = "httpd"
path = "src/httpd.rs"

[[bin]]
name = "input_dump"
path = "src/input_dump.rs"

[[bin]]
name = "h264_probe"
path = "src/h264_probe.rs"

[[bin]]
name = "lsm_list"
path = "src/lsm_list.rs"

[[bin]]
name = "lsm_unload"
path = "src/lsm_unload.rs"

[[bin]]
name = "lsm_load"
path = "src/lsm_load.rs"

[[bin]]
name = "socket_pair"
path = "src/socket_pair.rs"

[[bin]]
name = "socket_server"
path = "src/socket_server.rs"

[[bin]]
name = "socket_client"
path = "src/socket_client.rs"
